### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by cpy0029** [XiaoBuL/CM-UNet#1]
Can the processing code for masks_png_convert (converted masks used for training) in the LoveDA dataset and the train (processed) of Vaihingen and Potsdam datasets be made public? 
Thanks !!!

**Comment by cpy0029** [comment]
Or can use the dataset processed by mmseg for training?

**Comment by XiaoBuL** [comment]
Please follow the Geoseg's Dataset Preprocessing https://github.com/WangLibo1995/GeoSeg
