### ISSUE TITLE
LoveDA dataset

### ISSUE THREAD

**Issue by Assioncreed** [XiaoBuL/CM-UNet#10]
I would like to know what exactly the masks_png_convert and masks_png_convert_rgb folders in the LOVEDA dataset do with masks_png. Thanks.

**Comment by XiaoBuL** [comment]
It mainly converts the gray image masks_png to RGB colored image.

**Comment by 1pengliu** [comment]
> 它主要将灰度图像masks_png转换为 RGB 彩色图像。

<img width="273" alt="image" src="https://github.com/user-attachments/assets/a53e7209-10c6-40b5-978a-892932809df3">作者您好，请问将vaihingen数据下载下来后哪些是要复制到train_masks文件里，哪些要复制到test_masks_eroded文件夹里，分不清哪些是masks文件？original指的是TIFF的原始光学图像还是ground truth文件？
