### ISSUE TITLE
Where is CSMamba Block？

### ISSUE THREAD

**Issue by feng399-xinxin** [XiaoBuL/CM-UNet#3]
您好，请问CSMamba Block的代码在哪里，我没有找到加了channel attention和spatial attention后的vss block代码。谢谢！

**Comment by XiaoBuL** [comment]
Please refer to https://github.com/XiaoBuL/CM-UNet/blob/e0542d10eece62aa3aa89576afb1ee6b81dadd81/mamba_sys.py#L691

**Comment by feng399-xinxin** [comment]
Thank you !
