### ISSUE TITLE
Backbone pre-train weight

### ISSUE THREAD

**Issue by cpy0029** [XiaoBuL/CM-UNet#4]
>         self.backbone = timm.create_model("swsl_resnet18", features_only=True, output_stride=32,
>                                           out_indices=(1, 2, 3, 4),
>                                           pretrained=False)  # , pretrained_cfg_overlay=dict(file='~/.cache/huggingface/hub/models–timm– 
>                                           resnet18.a1_in1k/pytorch_model.bin'))        # build decoder layers
>         base_dims = 64
>         state_dict = torch.load('/data0/mushui/.cache/huggingface/hub/pytorch_model.bin')
>         msg = self.backbone.load_state_dict(state_dict, strict=False)
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/data0/mushui/.cache/huggingface/hub/pytorch_model.bin'

Can you provide the pre-trained weights of the backbone?

**Comment by fuxingfxy** [comment]
+1

**Comment by XiaoBuL** [comment]
Please download from the Baidu Pan, and modify the corresponding path. https://pan.baidu.com/s/1gGGxF1gOQM4MehRbm2jz1A?pwd=w6or
