### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by cpy0029** [XiaoBuL/CM-UNet#5]
>   File "/home/CM-UNet/cmunet/train_supervision.py", line 68, in training_step
>     self.metrics_train.add_batch(mask[i].cpu().numpy(), pre_mask[i].cpu().numpy())
>   File "/home/CM-UNet/cmunet/tools/metric.py", line 67, in add_batch
>     assert gt_image.shape == pre_image.shape, 'pre_image shape {}, gt_image shape {}'.format(pre_image.shape,
> AssertionError: pre_image shape (512,), gt_image shape (512, 512)

I encountered issues when training the LoveDA dataset, but this problem does not occur when training Potsdam.

**Comment by fuxingfxy** [comment]
I'm having this problem too.

**Comment by melooooody** [comment]
应该是https://github.com/XiaoBuL/CM-UNet/blob/e0542d10eece62aa3aa89576afb1ee6b81dadd81/cmunet/train_supervision.py#L55-L58 的原因，把辅助损失`use_aux_loss`设为False或者直接`pre_mask = nn.Softmax(dim=1)(prediction)`不会出现这个问题。

**Comment by cpy0029** [comment]
将config文件夹下mambaunet.py中的

> # from thop import profile
> # x = torch.randn(1, 3, 256, 256).cuda()
> # net.cuda()
> # net.eval()
> # # print(net.mamba_unet.flops())
> # out = net(x)
> # flops, params = profile(net, (x,))
> # print('flops:', flops / 1e9)
> # print('params:', params / 1e6)
> #
> # def get_model_memory_usage(model):
> #     total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
> #     total_buffers = sum(p.numel() for p in model.buffers())
> #     total_memory = total_params + total_buffers
> #     return total_memory
> #
> # memory_usage = get_model_memory_usage(net)
> # # 输出内存占用
> # print("Model memory usage:", memory_usage / 1024 / 1024, "MB")
注释掉就能运行了，训练时不需要设置use_aux_loss=False。 在需要测试flops时将注释取消并设置use_aux_loss=False即可。

**Comment by jawi289o** [comment]
@cpy0029 how did you run the model training? there is no cm-unet model in the geoseg file.
