### ISSUE TITLE
torchversion

### ISSUE THREAD

**Issue by Assioncreed** [XiaoBuL/CM-UNet#6]
Excuse me, is the torchversion fixed, windows can't install this version of torchversion. is it possible to use other versions of torch? thanks!

**Comment by XiaoBuL** [comment]
Maybe you can install the specific torchvision of the Windows version from this url : https://pytorch.org/get-started/previous-versions/.  Or you may run the repository on Linux to avoid unnecessary environment issues.

**Comment by Assioncreed** [comment]
Thanks
