### ISSUE TITLE
There was a problem with the environment installation. Torch1.10 was uninstalled due to the installation of the Lightning library.

### ISSUE THREAD

**Issue by GZ-YourZY** [XiaoBuL/CM-UNet#8]
Could you please make the library version list public? There was a problem during my installation. Torch1.10 was uninstalled due to the installation of the Lightning library and replaced with Torch2.3

**Comment by XiaoBuL** [comment]
I'm posting the list of installation packages, I hope this helps you.  
https://github.com/XiaoBuL/CM-UNet/blob/main/requirements.txt

**Comment by GuangzeShi** [comment]
> I'm posting the list of installation packages, I hope this helps you. https://github.com/XiaoBuL/CM-UNet/blob/main/requirements.txt

Thanks for your help, I will try these lists

**Comment by chengkai99** [comment]
# Editable install with no version control (apex==0.1)
-e /data0/mushui/apex-master 这儿报错

**Comment by 1pengliu** [comment]
> 我发布了安装包列表，希望对您有所帮助。 https://github.com/XiaoBuL/CM-UNet/blob/main/requirements.txt

<img width="1001" alt="image" src="https://github.com/user-attachments/assets/e490c6d3-3bc4-449e-9cc2-54b3196f15d5">
您好请问您遇到过此类问题吗？
