### ISSUE TITLE
geoseg一直是划红线的

### ISSUE THREAD

**Issue by FlowerRen** [XiaoBuL/CM-UNet#9]
from geoseg.losses import *
from geoseg.datasets.loveda_dataset import *
from geoseg.models.UNetFormer import UNetFormer
from geoseg.models.networks.vision_mamba import MambaUnet as VIM
你好，作者..我想问一下geoseg一直划红线，是因为那个包没有下载下来呢

**Comment by XiaoBuL** [comment]
You can change the directory name cmunet to geoseg to solve this issue.
